import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

/// Presentation use case that generates numbered marker icons for the
/// Google Map.
///
/// Each icon is a circular bitmap with the waypoint number drawn in the
/// center, matching the brand color palette. It stays in the presenter
/// (not in the domain) because it depends on the Flutter/Google Maps SDK
/// ([BitmapDescriptor]); the domain layer must remain framework-independent.
class NumberedMarkerUseCase {
  static const _size = 40.0;
  static const _fontSize = 20.0;

  /// Cached descriptors so the same number is not re-painted every rebuild.
  final Map<int, BitmapDescriptor> _cache = {};

  /// Returns a [BitmapDescriptor] with [number] drawn on a circular marker.
  ///
  /// The result is cached; repeated calls with the same number reuse the
  /// previously generated bytes.
  Future<BitmapDescriptor> execute(
    int number, {
    Color backgroundColor = Colors.red,
  }) async {
    final cached = _cache[number];
    if (cached != null) {
      return cached;
    }

    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    final center = Offset(_size / 2, _size / 2);

    // Shadow
    final shadowPaint = Paint()
      ..color = Colors.black38
      ..maskFilter = const ui.MaskFilter.blur(ui.BlurStyle.normal, 4);
    canvas.drawCircle(center.translate(0, 2), _size / 2, shadowPaint);

    // Circle background
    final paint = Paint()..color = backgroundColor;
    canvas.drawCircle(center, _size / 2, paint);

    // White border
    final borderPaint = Paint()
      ..color = Colors.white
      ..style = PaintingStyle.stroke
      ..strokeWidth = 4;
    canvas.drawCircle(center, _size / 2, borderPaint);

    // Number text
    final textPainter = TextPainter(
      text: TextSpan(
        text: '$number',
        style: const TextStyle(
          color: Colors.white,
          fontSize: _fontSize,
          fontWeight: FontWeight.bold,
        ),
      ),
      textDirection: TextDirection.ltr,
      textAlign: TextAlign.center,
    );
    textPainter.layout();
    textPainter.paint(
      canvas,
      Offset((_size - textPainter.width) / 2, (_size - textPainter.height) / 2),
    );

    final picture = recorder.endRecording();
    final image = await picture.toImage(_size.toInt(), _size.toInt());
    final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    final bytes = byteData!.buffer.asUint8List();

    final descriptor = BitmapDescriptor.bytes(bytes);
    _cache[number] = descriptor;
    return descriptor;
  }

  /// Clears the internal icon cache. Useful in tests.
  void clearCache() => _cache.clear();
}